version: '3.7'

x-app: &app
  image: timbru31/ruby-node
  # env_file:
  #   - .env
  volumes:
    - .:/app
    - node_modules:/app/node_modules/
    - gems:/usr/local/bundle

volumes:
  node_modules:
  gems:

services:
  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    build: .
    ports:
      - 3035:3035
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  web:
    <<: *app
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - webpacker
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
